version: "2"

networks:
  qm-intern:
  qm-reverse-proxy-interface:

services:
  qm-frontend:
    image: ghcr.io/meepmr/quizz-master-frontend:latest
    restart: always
    networks:
      - qm-intern
      - qm-reverse-proxy-interface
