name: Build and Test Project

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend
    steps:
      - uses: actions/checkout@v2
      - name: Npm Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run npm install
        run: npm install
        working-directory: ./quizz-master-frontend
      - name: Build Frontend
        run: npm run build
        working-directory: ./quizz-master-frontend

  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint Frontend
    steps:
      - uses: actions/checkout@v2
      - name: Npm Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run npm install
        run: npm install
        working-directory: ./quizz-master-frontend
      - name: Lint Frontend
        run: npm run lint
        working-directory: ./quizz-master-frontend

  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend
    steps:
      - uses: actions/checkout@v2
      - name: Npm Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run npm install
        run: npm install
        working-directory: ./quizz-master-frontend
      - name: Test Frontend
        run: npm run test
        working-directory: ./quizz-master-frontend

  test-backend:
    runs-on: ubuntu-latest
    name: Test Backend

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./quizz-master-backend
    - name: Test Backend
      run: ./gradlew check
      working-directory: ./quizz-master-backend

  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./quizz-master-backend
    - name: Test Backend
      run: ./gradlew bootJar
      working-directory: ./quizz-master-backend
