name: Build Docker Images

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-frontend-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
      working-directory: ./quizz-master-frontend/
    - name: build frontend
      run: npm run build
      working-directory: ./quizz-master-frontend/
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Authenticate To ghcr
      id: authenticate ghcr
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
      
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./quizz-master-frontend
        file: ./docker/qm-frontend/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/ppc64le
        push: true
        tags: latest
      
    #- name: push-to-ghcr
      # You may pin to the exact commit or the version.
      # uses: macbre/push-to-ghcr@d45c4b8f5a72d7fe21f6b832c42d05c29356c840
      #uses: macbre/push-to-ghcr@v8
     # with:
      #  # Your secrets.GITHUB_TOKEN
      #  github_token:  ${{ secrets.GITHUB_TOKEN }}
        # Image name, e.g. my-user-name/my-repo
      #  image_name: meepmr/quizz-master-frontend
        # A path to the Dockerfile (if it's not in the repository's root directory)
      #  dockerfile: ./docker/qm-frontend/Dockerfile
        # A path to the context in which the build will happen, see https://docs.docker.com/engine/reference/commandline/build/
       # context: ./quizz-master-frontend
