name: Build Docker Images

on:
  push:
    branches: [ master ]

jobs:
  set-version:
    runs-on: ubuntu-latest

    outputs:
      version-number: ${{ steps.get-version-number.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Read package version
        id: get-version-number
        run: PACKAGE_VERSION=$(head -n 1 version.txt) && echo ::set-output name=version::$PACKAGE_VERSION

  build-frontend-container:
    needs: set-version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Npm Setup
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install
      run: npm install
      working-directory: ./quizz-master-frontend/
    - name: build frontend
      run: npm run build
      working-directory: ./quizz-master-frontend/
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Authenticate To ghcr
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: meepmr
        password: ${{ secrets.GHCR_PAT }}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./quizz-master-frontend
        file: ./docker/qm-frontend.Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm
        push: true
        tags: |
          ghcr.io/meepmr/quizz-master-frontend:${{ needs.set-version.outputs.version-number }}
          ghcr.io/meepmr/quizz-master-frontend:latest

  build-backend-container:
    needs: set-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./quizz-master-backend
    - name: Build Backend
      run: ./gradlew bootJar
      working-directory: ./quizz-master-backend
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Authenticate To ghcr
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: meepmr
        password: ${{ secrets.GHCR_PAT }}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./quizz-master-backend
        file: ./docker/qm-backend.Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm
        push: true
        tags: |
          ghcr.io/meepmr/quizz-master-backend:${{ needs.set-version.outputs.version-number }}
          ghcr.io/meepmr/quizz-master-backend:latest

  trigger-bump_patch_version:
    needs: [build-backend-container, build-frontend-container]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Version Bump
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: bump_patch_version
